version: "3.5"
services: 
  back_end:
    container_name: backend_service_dev
    build: 
      dockerfile: docker-dev.Dockerfile
      context: ./back-end
    depends_on: 
      - data_base
    volumes: 
      - ./back-end:/usr/app
      - /usr/app/node_modules
    command: npm run dev
    environment: 
      - MONGO_URL=mongodb://dataBase:27017/app
      - APP_PORT=8000
    ports: 
      - 8000:3000
  front_end:
    container_name: front_end_service_dev
    volumes: 
      - ./front-end:/usr/front-end
      - /usr/front-end/node_modules
    build:
      context: ./front-end
      dockerfile: docker-dev.Dockerfile
    ports: 
      - 8005:8080