
  backend:
  container_name: backend_service
  build: 
    context: ./back-end
  depends_on: 
    - dataBase
  volumes: 
    - ./back-end:/usr/app
    - /usr/app/node_modules
  command: npm run dev
  environment: 
    - MONGO_URL=mongodb://dataBase:27017/app
    - APP_PORT=8000
  ports: 
    - 8000:8000
front_end:
  container_name: front_end_service
  volumes: 
    - ./front-end:/usr/front-end
    - /usr/front-end/node_modules
  build:
    context: ./front-end
    dockerfile: ./front-end/docker-dev.Dockerfile
  ports: 
    - 80001:8080
  environment: 
    - BACKEND_URL=http://localhost/app