version: "3.5"

services: 
  back_end:
    container_name: backend_service
    build: 
      context: ./back-end
    depends_on: 
      - data_base
    volumes: 
      - ./back-end:/usr/app
      - /usr/app/node_modules
    environment: 
      - MONGO_URL=mongodb://dataBase:27017/app
      - APP_PORT=8000
    ports: 
      - 8000:8000
  data_base:
    container_name: data_base_service
    image: mongo
    restart: always
  front_end:
    container_name: front_end_service
    build: 
      context: ./front-end
    ports: 
      - 80001:8080
    environment: 
      - BACKEND_URL=http://localhost/app