version: "3.5"
services: 
  backend:
    container_name: backend_service_dev
    build: 
      context: ./back-end
    depends_on: 
      - data_base
    volumes: 
      - ./back-end:/usr/app
      - /usr/app/node_modules
    command: npm run dev
    environment: 
      - MONGO_URL=mongodb://dataBase:27017/app
      - APP_PORT=8000
    ports: 
      - 8000:8000
  front_end:
    container_name: front_end_service_dev
    volumes: 
      - ./front-end:/usr/front-end
      - /usr/front-end/node_modules
    build:
      context: ./front-end
      dockerfile: docker-dev.Dockerfile
    ports: 
      - 8080:8080
    environment: 
      - BACKEND_URL=http://localhost/app